spring.application.name=backend

# Server Port Configuration
server.port=8080

# MySQL Connection Settings
spring.datasource.url=jdbc:mysql://localhost:3306/student_tracker
spring.datasource.username=root
spring.datasource.password=03@Maimela
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Hibernate MySQL Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Disable OSIV warning
spring.jpa.open-in-view=false

# Security settings
spring.security.user.name=root
spring.security.user.password=03@Maimela

logging.level.org.springframework.security=DEBUG